<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServiceSeeder extends Seeder
{
    public function run(): void
    {
        $services = [
            // Office 1 - CMO (Office of the City Mayor)
            ['office_id' => 1, 'service_name' => 'Issuance of Mayor\'s Clearance', 'service_code' => 'MC', 'service_description' => 'Isang sertipikong nagpapatunay na ang isang indibidwal ay walang nakabinbing obligasyon, paglabag, o derogatory record sa lokal na pamahalaan. Karaniwang requirement ito para sa trabaho, transaksyong pangnegosyo, loan application, at iba pang legal o opisyal na layunin.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 1, 'service_name' => 'Issuance of Permit to Conduct Motorcade or Parade', 'service_code' => 'PCMP', 'service_description' => 'Kinakailangang kumuha ng Mayor\'s Permit ang mga nais magsagawa ng motorcade o parada upang matiyak ang maayos at mapayapang pagsasagawa ng aktibidad.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 1, 'service_name' => 'Receiving of Communications and Letters', 'service_code' => 'RCL', 'service_description' => 'Tumatanggap ang Administrative Section ng mga sulat at komunikasyon mula sa mga ahensya ng gobyerno, ibang LGU, pribadong establisyemento, at publiko para sa kaukulang aksyon ng Local Chief Executive (LCE).', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 1, 'service_name' => 'Issuance of Endorsement or Recommendations for Employment', 'service_code' => 'ERE', 'service_description' => 'Serbisyong ina-avail ng mga residente ng Ligao City na nag-aapply sa mga pambansang ahensya tulad ng PNP, BFP, BJMP, at iba pa.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 1, 'service_name' => 'Issuance of Certificate of Appearance', 'service_code' => 'CA', 'service_description' => 'Ibinibigay sa mga kliyenteng bumisita sa tanggapan para sa opisyal na transaksyon, kabilang ang mga mula sa LGU, national agencies, barangay, at pribadong sektor.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 1, 'service_name' => 'Documents for City Mayor\'s Signature', 'service_code' => 'DCMS', 'service_description' => 'Tumatanggap ng mga dokumento tulad ng payroll, vouchers, kontrata, purchase request, tseke, at iba pang komunikasyon para sa pirma, pag-apruba, o kaukulang aksyon ng LCE.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 1, 'service_name' => 'Issuance of Mayor\'s Permit for Use of Government Facilities', 'service_code' => 'PUGF', 'service_description' => 'Para sa mga humihiling na gamitin ang City Gymnasium o City Pavilion para sa mga espesyal na pagtitipon at okasyon.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 1, 'service_name' => 'Issuance of Mayor\'s Permit for Promotional Activities', 'service_code' => 'MPPA', 'service_description' => 'Ibinibigay sa mga negosyong nais magsagawa ng promotional activities sa loob ng lungsod.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 1, 'service_name' => 'Issuance of Permit to Conduct Social Dances', 'service_code' => 'PCSD', 'service_description' => 'Kinakailangang kumuha ng permit mula sa City Mayor\'s Office upang matiyak ang maayos at mapayapang pagsasagawa ng social dances sa mga barangay.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 1, 'service_name' => 'Issuance of Special Permit', 'service_code' => 'SP', 'service_description' => 'Ibinibigay para sa pagsasagawa ng sabong (cockfighting).', 'service_type' => 'External', 'classification' => 'Complex', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 1, 'service_name' => 'Approval and Issuance of Foreign Travel Authority', 'service_code' => 'FTA', 'service_description' => 'Ibinibigay sa mga opisyal at empleyado ng City Government na humihiling ng pahintulot na maglakbay sa labas ng Pilipinas para sa personal na dahilan.', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 1, 'service_name' => 'Vehicle Request from Various Offices/Departments', 'service_code' => 'VRQ', 'service_description' => 'Pinadadali ang pag-request at paglalaan ng opisyal na sasakyan para sa mga awtorisadong aktibidad, pagpupulong, fieldwork, at iba pang gawaing pang-gobyerno.', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 1, 'service_name' => 'Documents for City Mayor\'s Signature - Internal', 'service_code' => 'DCMS-I', 'service_description' => 'Tumatanggap ng mga dokumento tulad ng payroll, vouchers, kontrata, purchase request, tseke, at iba pang komunikasyon para sa pirma, pag-apruba, o kaukulang aksyon ng LCE.', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],

            // Office 2 - CML (Library Services)
            ['office_id' => 2, 'service_name' => 'Issuance of Library Membership Form and Library ID Card', 'service_code' => 'ILMF-LIC', 'service_description' => 'Pagbibigay ng membership form at ID ng aklatan para sa mga nais maging rehistradong miyembro.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 2, 'service_name' => 'Borrowing of Books and Other Library Materials', 'service_code' => 'BBLM', 'service_description' => 'Pagpapahiram ng mga aklat at iba pang materyales sa mga rehistradong miyembro.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 2, 'service_name' => 'Children\'s Services', 'service_code' => 'CS', 'service_description' => 'Pagbibigay ng mga programang pangbata tulad ng pagbabasa at edukasyonal na gawain.', 'service_type' => 'External', 'classification' => 'Complex', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 2, 'service_name' => 'Acceptance of Donations', 'service_code' => 'AD', 'service_description' => 'Pagtanggap ng donasyon ng mga aklat at iba pang materyales para sa aklatan.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],

            // Office 3 - CM-LiComCo (Ligao Community College)
            ['office_id' => 3, 'service_name' => 'Application for OTR, Certifications, and Honorable Dismissal (Graduates & Non-Graduates)', 'service_code' => 'AOTR-CHD', 'service_description' => 'Pagproseso ng OTR, certifications, at honorable dismissal para sa mga estudyante.', 'service_type' => 'External', 'classification' => 'Highly_Technical', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 3, 'service_name' => 'Re-Issuance or Replacement of Lost or Damaged Diploma', 'service_code' => 'RIRD', 'service_description' => 'Pagpapalit o muling pagkuha ng nawala o nasirang diploma.', 'service_type' => 'External', 'classification' => 'Highly_Technical', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 3, 'service_name' => 'Application for Certification, Authentication, and Verification (CAV)', 'service_code' => 'CAV', 'service_description' => 'Pagproseso ng CAV para sa CHED at DFA na layunin.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 3, 'service_name' => 'Authentication and Certifying of School Photocopied Documents', 'service_code' => 'ACSD', 'service_description' => 'Pagpapatunay at pag-certify ng mga photocopied na dokumento ng paaralan.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 3, 'service_name' => 'Application for World Education Services (WES) Education Verification', 'service_code' => 'WES-EV', 'service_description' => 'Pagproseso ng education verification para sa WES Canada.', 'service_type' => 'External', 'classification' => 'Complex', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 3, 'service_name' => 'Issuance of Books Borrowed', 'service_code' => 'IBB', 'service_description' => 'Pagpapahiram at pag-isyu ng mga aklat sa mga estudyante.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 3, 'service_name' => 'Issuance of Good Moral Character', 'service_code' => 'IGMC', 'service_description' => 'Pagbibigay ng sertipikong nagpapatunay ng mabuting asal ng estudyante.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 3, 'service_name' => 'Availing Medical Services and Healthcare', 'service_code' => 'AMSH', 'service_description' => 'Pagbibigay ng serbisyong medikal at pangkalusugan sa mga estudyante.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],

            // Office 4 - CGSO (City General Services Office) - External
            ['office_id' => 4, 'service_name' => 'Assistance for Academic, Social, Peace and Order, Sports and Development Program', 'service_code' => 'AASPOSDP', 'service_description' => 'Pagbibigay ng suporta sa mga programang akademiko, panlipunan, at pangkaunlaran.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 4, 'service_name' => 'Assistance for the Repair and Maintenance of Government Owned Structures', 'service_code' => 'ARMGOS', 'service_description' => 'Suporta sa pagkukumpuni at pagpapanatili ng mga gusaling pag-aari ng pamahalaan.', 'service_type' => 'External', 'classification' => 'Highly_Technical', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 4, 'service_name' => 'Payments for Utilities and Bills', 'service_code' => 'PUB', 'service_description' => 'Pagproseso ng bayarin para sa kuryente, tubig, at iba pang utilities.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 4, 'service_name' => 'Assistance for Janitorial, Utility, Technical Services, and Equipment', 'service_code' => 'AJUTSE', 'service_description' => 'Pagbibigay ng suporta sa janitorial, technical services, at kagamitan.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 4, 'service_name' => 'Cancellation of Property Acknowledgement and Receipt', 'service_code' => 'CPAR', 'service_description' => 'Pagproseso ng pagkansela ng Property Acknowledgement Receipt (PAR).', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],

            // Office 4 - CGSO (Internal)
            ['office_id' => 4, 'service_name' => 'Assistance for the Repair and Maintenance of Government Owned Structures - Internal', 'service_code' => 'ARMGOS-I', 'service_description' => 'Suporta sa pagkukumpuni at pagpapanatili ng mga gusaling pag-aari ng pamahalaan.', 'service_type' => 'Internal', 'classification' => 'Highly_Technical', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 4, 'service_name' => 'Procurement Process', 'service_code' => 'PP', 'service_description' => 'Pagproseso ng pagbili ng mga kagamitan, suplay, at serbisyo ng pamahalaan.', 'service_type' => 'Internal', 'classification' => 'Complex', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 4, 'service_name' => 'Repair and Maintenance of Vehicles and Equipment', 'service_code' => 'RMVE', 'service_description' => 'Pagkukumpuni at pagpapanatili ng mga sasakyan at kagamitan ng lungsod.', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 4, 'service_name' => 'Preparation and Transfer of Property Acknowledgement Receipt (PAR) / Inventory Custodian Slip (ICS)', 'service_code' => 'PT-PAR/ICS', 'service_description' => 'Paghahanda at paglilipat ng PAR at ICS para sa wastong pagtatalaga ng mga kagamitan.', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],

            // Office 5 - CLCR (City Local Civil Registrar)
            ['office_id' => 5, 'service_name' => 'Timely Registration of Birth', 'service_code' => 'TRB', 'service_description' => 'Ang lahat ng sanggol na isang buwan at mas bata pa ay dapat i-report at irehistro gamit ang prescribed Certificate of Live Birth (COLB) upang mailahad ang mga katotohanan at pangyayari kaugnay ng kapanganakan ng isang tao.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => false, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 5, 'service_name' => 'Delayed Registration of Birth', 'service_code' => 'DRB', 'service_description' => 'Ang lahat ng hindi pa nairehistrong kapanganakan ng isang indibidwal na higit sa isang buwan ang edad ay dapat i-report at irehistro gamit ang prescribed COLB para sa deklarasyon ng mga katotohanan at pangyayari kaugnay ng kapanganakan.', 'service_type' => 'External', 'classification' => 'Complex', 'is_free' => false, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 5, 'service_name' => 'Timely Registration of Death', 'service_code' => 'TRD', 'service_description' => 'Ang lahat ng kamatayan ay dapat i-report at irehistro sa loob ng isang buwan pagkatapos mangyari gamit ang prescribed Certificate of Death (COD) para sa deklarasyon ng mga katotohanan at pangyayari kaugnay ng kamatayan.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => false, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 5, 'service_name' => 'Delayed Registration of Death', 'service_code' => 'DRD', 'service_description' => 'Ang lahat ng kamatayan ay dapat i-report at irehistro gamit ang COD, kahit na lampas na sa isang buwan mula sa pagkamatay, para sa deklarasyon ng mga katotohanan at pangyayari.', 'service_type' => 'External', 'classification' => 'Complex', 'is_free' => false, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 5, 'service_name' => 'Timely Registration of Marriage', 'service_code' => 'TRM', 'service_description' => 'All marriage concluded within 15 days must be reported and registered using the prescribed Certificate of Marriage (COM) for declaration of facts and circumstances surrounding the marriage of a couple.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => false, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 5, 'service_name' => 'Delayed Registration of Marriage', 'service_code' => 'DRM', 'service_description' => 'All marriage concluded after 15 days must be reported and registered using the prescribed Certificate of Marriage (COM) for declaration of facts and circumstances surrounding the marriage of a couple.', 'service_type' => 'External', 'classification' => 'Complex', 'is_free' => false, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 5, 'service_name' => 'Issuance of Certification of Civil Registry Documents', 'service_code' => 'CCRD', 'service_description' => 'Pagbibigay ng sertipikasyon para sa mga dokumentong mula sa Civil Registry.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => false, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 5, 'service_name' => 'Processing of Request for Birth, Marriage, Death Not Found in PSA Database', 'service_code' => 'PR-BMD', 'service_description' => 'Pagproseso ng kahilingan para sa mga Birth, Marriage, at Death records na wala sa talaan ng PSA.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => false, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 5, 'service_name' => 'Processing of Supplemental Report', 'service_code' => 'PSR', 'service_description' => 'Pagproseso ng kahilingan upang idagdag ang nawawalang impormasyon sa COLB, COD, o COM. Kapag tatlo o higit pang entry ang nawawala, kinakailangan ang pag-apruba ng PSA bago ilabas ang dokumento; kung hindi, apruba lamang ng City Civil Registrar ang kailangan.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => false, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 5, 'service_name' => 'Processing of Application for Marriage License', 'service_code' => 'AML', 'service_description' => 'Pagproseso at pagbibigay ng marriage license para sa mga nasa legal na edad at walang hadlang sa kasal.', 'service_type' => 'External', 'classification' => 'Complex', 'is_free' => false, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 5, 'service_name' => 'Petition for Correction of Clerical Error (RA 9048 & RA 10172)', 'service_code' => 'PCCE', 'service_description' => 'Pagproseso ng pagwawasto ng clerical errors at pagbabago ng pangalan, kasarian, o petsa sa Civil Registry Documents ayon sa RA 9048 at RA 10172 nang hindi na kailangan ng korte.', 'service_type' => 'External', 'classification' => 'Complex', 'is_free' => false, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 5, 'service_name' => 'Registration of Court Decree/Order and Legal Instruments', 'service_code' => 'CDLI', 'service_description' => 'Pagpaparehistro ng mga desisyon ng korte sa adoption, annulment, o pagbabago ng nationality/petsa ng kapanganakan, pati na rin ng mga dokumentong tulad ng Affidavit of Legitimation, Authority to Use Father\'s Surname (AUSF), at Admission of Paternity.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => false, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 5, 'service_name' => 'Application for Legitimation and Authority to Use Father\'s Surname', 'service_code' => 'AL-AUSF', 'service_description' => 'Pagproseso ng aplikasyon para sa legitimation at paggamit ng apelyido ng ama.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => false, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],

            // Office 6 - CTO (City Treasurer's Office)
            ['office_id' => 6, 'service_name' => 'Real Property Tax Clearance', 'service_code' => 'RPTC', 'service_description' => 'Pagbibigay ng clearance para sa Real Property Tax ng ari-arian.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 6, 'service_name' => 'Real Property Tax Payment', 'service_code' => 'RPTP', 'service_description' => 'Pagbabayad ng buwis sa ari-arian sa lungsod.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 6, 'service_name' => 'Payment of Real Property Transfer Tax', 'service_code' => 'PRPTT', 'service_description' => 'Pagbabayad ng buwis sa paglilipat ng ari-arian.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 6, 'service_name' => 'Sealing of Weights and Measures', 'service_code' => 'SWM', 'service_description' => 'Pagpapatunay at pagsasaayos ng timbang at sukat ng gamit sa kalakalan.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 6, 'service_name' => 'Issuance of Community Tax Certificate', 'service_code' => 'ICTC', 'service_description' => 'Pagbibigay ng sertipiko bilang patunay ng pagbabayad ng community tax.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 6, 'service_name' => 'Payment of Other Taxes, Fees, and Charges', 'service_code' => 'PTFC', 'service_description' => 'Pagbabayad ng iba pang buwis, bayarin, at singil ng lungsod.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 6, 'service_name' => 'Generation of Etracs Report', 'service_code' => 'GER', 'service_description' => 'Paggawa ng Etracs report para sa buwis at rekord ng ari-arian.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 6, 'service_name' => 'Issuance of Certificate of Ownership and Transfer of Large Cattle', 'service_code' => 'CO/CTLC', 'service_description' => 'Pagbibigay ng sertipiko para sa pagmamay-ari at paglilipat ng malalaking hayop.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 6, 'service_name' => 'Releasing of Check Payments', 'service_code' => 'RCP', 'service_description' => 'Pagpapalabas ng tseke para sa bayad o reimbursement.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 6, 'service_name' => 'Payments of Assistance to Individual in Crisis Situation (AICS) and Cash Incentive to Senior Citizens Celebrating Milestone Birthdays', 'service_code' => 'AICS/CSI', 'service_description' => 'Pagbibigay ng tulong-pinansyal sa mga indibidwal sa krisis at cash incentive sa senior citizens sa kanilang milestone birthdays.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 6, 'service_name' => 'Payment of Payrolls', 'service_code' => 'POP', 'service_description' => 'Pagproseso at pagbabayad ng sahod ng mga empleyado ng lungsod.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 6, 'service_name' => 'Releasing of Check Payments - Internal', 'service_code' => 'RCPI', 'service_description' => 'Pagpapalabas ng tseke para sa bayad o reimbursement.', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 6, 'service_name' => 'Payment of Payrolls - Internal', 'service_code' => 'POP-I', 'service_description' => 'Pagproseso at pagbabayad ng sahod ng mga empleyado ng lungsod.', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],

            // Office 7 - CTO-OEE (City Treasurer's Office - Office of the Economic Enterprise)
            ['office_id' => 7, 'service_name' => 'Issuance of Contract of Lease for NE Burial Plot', 'service_code' => 'ICL-NEBP', 'service_description' => 'Pagbibigay ng kontrata para sa pag-upa ng Non-Exclusively designated burial plot.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 7, 'service_name' => 'Issuance of Contract of Lease to Renewable Burial Plot', 'service_code' => 'ICL-RBP', 'service_description' => 'Pagbibigay ng kontrata para sa renewable burial plot.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 7, 'service_name' => 'Issuance of Mayor\'s Permit for Skeletal Remains Transfer to Ossuary Type', 'service_code' => 'IMP-SRTO', 'service_description' => 'Pagproseso ng permit para sa paglilipat ng labi.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 7, 'service_name' => 'Market Rental Field Collection', 'service_code' => 'MRFC', 'service_description' => 'Pangongolekta ng renta sa palengke.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 7, 'service_name' => 'Slaughterhouse Collection', 'service_code' => 'SC', 'service_description' => 'Pangongolekta ng bayad sa slaughterhouse.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 7, 'service_name' => 'Ligao Community College Fees and Charges', 'service_code' => 'LC-FC', 'service_description' => 'Pangongolekta ng school fees.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],

            // Office 8 - CAO (City Assessor's Office)
            ['office_id' => 8, 'service_name' => 'Issuance of Certified True Copy of Tax Declaration (Latest and Previous)', 'service_code' => 'CTC-TD', 'service_description' => 'Pagbibigay ng certified copy.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 8, 'service_name' => 'Issuance of Certificate of Property Landholdings or Insolvency', 'service_code' => 'CPL', 'service_description' => 'Pagbibigay ng sertipiko.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 8, 'service_name' => 'Issuance of Certificate of No Improvement', 'service_code' => 'CNI', 'service_description' => 'Pagpapatunay na walang improvement.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 8, 'service_name' => 'Transfer of Tax Declarations to the New Owner', 'service_code' => 'TTD-NO', 'service_description' => 'Paglipat ng tax declaration.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 8, 'service_name' => 'Subdivision/Segregation of Tax Declarations', 'service_code' => 'SSD-TD', 'service_description' => 'Paghiwa-hiwalay ng lote.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 8, 'service_name' => 'Consolidation of Tax Declarations', 'service_code' => 'CTD', 'service_description' => 'Pagsasama ng tax declarations.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 8, 'service_name' => 'Annotation of Tax Declarations', 'service_code' => 'ATD', 'service_description' => 'Paglalagay ng annotation.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 8, 'service_name' => 'Verification of Lot Location/Boundaries/Issuance of Cert. of Tax Map', 'service_code' => 'VL-CTM', 'service_description' => 'Pag-verify ng lot location.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 8, 'service_name' => 'Cancellation, Correction and Reassessment of Real Property', 'service_code' => 'CCRA-RP', 'service_description' => 'Pagwawasto ng property record.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 8, 'service_name' => 'Assessment of Real Property (Land, Building and Machineries)', 'service_code' => 'ARP', 'service_description' => 'Pagtataya ng property.', 'service_type' => 'External', 'classification' => 'Complex', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 8, 'service_name' => 'Lot History Verification of Property (Research/Traceback of Tax Declaration)', 'service_code' => 'LHVP', 'service_description' => 'Pag-verify ng history ng lote.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],

            // Office 9 - BPLO
            ['office_id' => 9, 'service_name' => 'Issuance of Business Permit', 'service_code' => 'IBP', 'service_description' => 'Pagbibigay ng permit sa negosyo.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],

            // Office 10 - CENRO
            ['office_id' => 10, 'service_name' => 'Issuance of ENRO Certificate for Business Permit', 'service_code' => 'CENRO-CBP', 'service_description' => 'Requirement sa permit.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 10, 'service_name' => 'Issuance of Certificate of No Objection for Tree Cutting', 'service_code' => 'CNO-TC', 'service_description' => 'Permit sa tree cutting.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 10, 'service_name' => 'Granting of Free Seedlings', 'service_code' => 'GFS', 'service_description' => 'Pamamahagi ng punla.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 10, 'service_name' => 'Fisherfolk Registration', 'service_code' => 'FR', 'service_description' => 'Pagrehistro ng mangingisda.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 10, 'service_name' => 'Fishing Vessel and Gear Registration and Permit to Fish (New Application)', 'service_code' => 'FVGRPF-NA', 'service_description' => 'New registration.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 10, 'service_name' => 'Fishing Vessel and Gear Registration and Permit to Fish (Renewal)', 'service_code' => 'FVGRPF-R', 'service_description' => 'Renewal registration.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],

            // Office 11 - CEO (City Engineering Office)
            ['office_id' => 11, 'service_name' => 'Processing of Documents for the Release of Payment for Infrastructure Projects', 'service_code' => 'PDRPIP', 'service_description' => 'Pagproseso ng dokumento para sa bayad ng infrastructure projects.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 11, 'service_name' => 'Issuance of Final Acceptance Certificate', 'service_code' => 'IFAC', 'service_description' => 'Pagbibigay ng final acceptance certificate.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 11, 'service_name' => 'Issuance of Barangay Certificate for Barangay Completed Project', 'service_code' => 'IBCCP', 'service_description' => 'Pagbibigay ng certificate para sa completed project.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 11, 'service_name' => 'Issuance of Site Inspection Certificate', 'service_code' => 'ISIC', 'service_description' => 'Pagbibigay ng inspection certificate.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],

            // Office 12 - CCDO (City Cooperative Development Office)
            ['office_id' => 12, 'service_name' => 'Cooperative Organization and Development', 'service_code' => 'COD', 'service_description' => 'Pagpapaunlad ng cooperatives.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 12, 'service_name' => 'Tricycle Boundary Hulog Project Livelihood Assistance', 'service_code' => 'TBHPLA', 'service_description' => 'Tulong sa tricycle sector.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 12, 'service_name' => 'Skills Training', 'service_code' => 'ST', 'service_description' => 'Skills training program.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 12, 'service_name' => 'Issuance of Training Certificate', 'service_code' => 'ITC', 'service_description' => 'Certificate ng training.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],

            // Office 13 - CLO (City Legal Office)
            ['office_id' => 13, 'service_name' => 'Deed of Absolute Sale/Deed of Donation/Deed of Extrajudicial Settlement of Estate with Deed of Absolute Sale', 'service_code' => 'DAS-DOD-EJS', 'service_description' => 'Legal documents preparation.', 'service_type' => 'External', 'classification' => 'Complex', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 13, 'service_name' => 'For Drafting or Review of Memorandum of Agreement', 'service_code' => 'DR-MOA', 'service_description' => 'MOA review.', 'service_type' => 'External', 'classification' => 'Complex', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 13, 'service_name' => 'For the Drafting of Legal Research and/or the Rendering of Legal Opinion', 'service_code' => 'LRLO', 'service_description' => 'Legal research services.', 'service_type' => 'External', 'classification' => 'Complex', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 13, 'service_name' => 'For Review of Communication Letter', 'service_code' => 'RCL', 'service_description' => 'Letter review.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 13, 'service_name' => 'For Drafting or Review of Memorandum of Agreement - Internal', 'service_code' => 'DR-MOA-I', 'service_description' => 'Internal MOA review.', 'service_type' => 'Internal', 'classification' => 'Complex', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 13, 'service_name' => 'For the Drafting of Legal Research and/or the Rendering of Legal Opinion - Internal', 'service_code' => 'LRLO-I', 'service_description' => 'Internal legal opinion.', 'service_type' => 'Internal', 'classification' => 'Complex', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 13, 'service_name' => 'For Review of Communication Letter - Internal', 'service_code' => 'RCL-I', 'service_description' => 'Internal letter review.', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 13, 'service_name' => 'Signing of Clearances (CS Form No. 7, Series of 2017)', 'service_code' => 'SOC', 'service_description' => 'Approval of clearances.', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],

            // Office 14 - ADMIN (Administrative Office)
            ['office_id' => 14, 'service_name' => 'Preparation of Communication Letters', 'service_code' => 'PCL', 'service_description' => 'Preparation of official letters.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 14, 'service_name' => 'Acquisition of Real Property By The City Government of Ligao', 'service_code' => 'ARP', 'service_description' => 'Pagkuha ng lupa ng LGU.', 'service_type' => 'External', 'classification' => 'Highly_Technical', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 14, 'service_name' => 'Posting/Issuance of Certificates of Posting', 'service_code' => 'PICP', 'service_description' => 'Posting certification.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 14, 'service_name' => 'Approving and signing of Disbursement Voucher and Obligation Request for Summary of Payroll and Utilities', 'service_code' => 'ASDVOR', 'service_description' => 'Approval of vouchers.', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 14, 'service_name' => 'Preparation of Communication Letters - Internal', 'service_code' => 'PCL-I', 'service_description' => 'Internal letters.', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],

            // Office 15 - CHO (City Health Office)
            ['office_id' => 15, 'service_name' => 'National TB Control Program', 'service_code' => 'NTBCP', 'service_description' => 'TB program.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 15, 'service_name' => 'National Immunization Program', 'service_code' => 'NIP', 'service_description' => 'Vaccination services.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 15, 'service_name' => 'Provision of Pre-natal Care, Post-natal and Mother\'s Class', 'service_code' => 'PNC', 'service_description' => 'Maternal care.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 15, 'service_name' => 'Normal Spontaneous Delivery and Newborn Care', 'service_code' => 'NSD-NBC', 'service_description' => 'Delivery services.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 15, 'service_name' => 'Family Planning', 'service_code' => 'FP', 'service_description' => 'Family planning services.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 15, 'service_name' => 'Pre-Marriage Counseling', 'service_code' => 'PMC', 'service_description' => 'Marriage counseling.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 15, 'service_name' => 'Donor Recruitment and Blood Collection', 'service_code' => 'DRBC', 'service_description' => 'Blood donation.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 15, 'service_name' => 'Physical Therapy Center', 'service_code' => 'PTC', 'service_description' => 'Rehabilitation services.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 15, 'service_name' => 'Medical Consultation', 'service_code' => 'MC', 'service_description' => 'Konsultasyong medikal na isinasagawa ng City Health Officer o Rural Health Physician para sa lahat ng Ligaoeño.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 15, 'service_name' => 'Issuance of Sanitary Permit and Health Certificate', 'service_code' => 'ISPHC', 'service_description' => 'Alinsunod sa Sanitation Code of the Philippines o P.D. 856.', 'service_type' => 'External', 'classification' => 'Complex', 'is_free' => false, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 15, 'service_name' => 'Health Services to DepEd', 'service_code' => 'HSD', 'service_description' => 'Medikal na eksaminasyon para sa mga Senior High School students, pagbibigay ng medical clearance at multivitamins para sa mga atleta.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 15, 'service_name' => 'Rabies Prevention and Control Program', 'service_code' => 'RPCP', 'service_description' => 'Layuning maiwasan at makontrol ang rabies sa pamamagitan ng pagbibigay at pagtataguyod ng accessible na bakuna, kasama ang edukasyon at pagpapalaganap ng kaalaman tungkol sa rabies.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 15, 'service_name' => 'Noncommunicable Disease Prevention and Control Program (Lifestyle Related Disease and Risk Factor Program)', 'service_code' => 'NDPCP', 'service_description' => 'Nakatuon sa pag-iwas, maagang pagtuklas, paggamot, at pamamahala ng mga sakit na hindi nakahahawa tulad ng cardiovascular diseases, diabetes, cancer, chronic respiratory diseases, at mental health disorders.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 15, 'service_name' => 'Smoke Free Program', 'service_code' => 'SFP', 'service_description' => 'Nagbibigay ng smoking cessation services, tumutulong sa pagtigil ng paninigarilyo, at nagbababala tungkol sa masamang epekto ng tabako.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 15, 'service_name' => 'Adolescents Health and Development Program', 'service_code' => 'AHDP', 'service_description' => 'Kasama ang general health assessment, dental assessment, psychosocial risk assessment o HEADSS, nutrition assessment at counseling, micronutrient supplementation, immunization, basic diagnostic tests tulad ng CBC at urinalysis, sexual and reproductive health counseling kabilang ang family planning services, voluntary counseling and testing para sa STIs at HIV, pre/intra/postnatal services, at pag-iwas sa teenage pregnancy.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 15, 'service_name' => 'STI/HIV/AIDS Prevention and Control Program', 'service_code' => 'STI-HIV-AIDS', 'service_description' => 'Namamahala sa pag-iwas, paggamot, at pagkontrol ng sexually transmitted infections kabilang ang HIV, at pagbibigay ng diagnostic assessment, treatment and care, pati na rin health education at counseling.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 15, 'service_name' => 'National Dengue Prevention and Control Program', 'service_code' => 'NDPC', 'service_description' => 'Layuning mabawasan ang kaso at pagkamatay dahil sa dengue sa pamamagitan ng aktibong surveillance, tamang case management at diagnosis, vector control sa komunidad, at health education.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 15, 'service_name' => 'Laboratory Diagnostic Test/Urinalysis', 'service_code' => 'LDT', 'service_description' => 'Ang Laboratoryo ng City Health Office ay nagsasagawa ng iba\'t ibang pagsusuring medikal tulad ng urinalysis, upang makatulong sa tamang diagnosis at gamutan ng mga pasyente.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 15, 'service_name' => 'Sputum Examination (Direct Sputum Smear Microscopy)', 'service_code' => 'SE', 'service_description' => 'Ang Laboratoryo ng City Health Office ay nagsasagawa ng iba\'t ibang pagsusuring medikal tulad ng sputum examination, upang makatulong sa tamang diagnosis at gamutan ng mga pasyente.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 15, 'service_name' => 'Hemoglobin Test', 'service_code' => 'HT', 'service_description' => 'Ang Laboratoryo ng City Health Office ay nagsasagawa ng iba\'t ibang pagsusuring medikal tulad ng hemoglobin test, upang makatulong sa tamang diagnosis at gamutan ng mga pasyente.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 15, 'service_name' => 'Stool Examination/Fecalysis', 'service_code' => 'SE/F', 'service_description' => 'Ang Laboratoryo ng City Health Office ay nagsasagawa ng iba\'t ibang pagsusuring medikal tulad ng fecalysis, upang makatulong sa tamang diagnosis at gamutan ng mga pasyente.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 15, 'service_name' => 'CBC - Complete Blood Count', 'service_code' => 'CBC', 'service_description' => 'Ang Laboratoryo ng City Health Office ay nagsasagawa ng iba\'t ibang pagsusuring medikal tulad ng CBC, upang makatulong sa tamang diagnosis at gamutan ng mga pasyente.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 15, 'service_name' => 'Senior Citizen\'s Clinic', 'service_code' => 'SCC', 'service_description' => 'Layuning itaguyod ang malusog na pagtanda, pag-iwas sa sakit, at maayos na pamamahala ng mga chronic condition.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 15, 'service_name' => 'Post Mortem, Autopsy or Necropsy', 'service_code' => 'PMAN', 'service_description' => 'Pagsasagawa ng post mortem, autopsy, o necropsy sa mga hindi inaasahang pagkamatay na naganap sa labas ng ospital ngunit sakop ng Lungsod ng Ligao, tulad ng aksidente sa kalsada o insidente ng pagpapakamatay', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 15, 'service_name' => 'Examination of Medico Legal Cases', 'service_code' => 'EMLC', 'service_description' => 'Pisikal at/o genital na pagsusuri para sa mga biktima ng medico-legal cases.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => false, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 15, 'service_name' => 'Medical Certificates for Employment/Medical Assistance & Other Purpose', 'service_code' => 'MCE/MA', 'service_description' => 'Pagbibigay ng medical certificate na pirmado at sertipikado ng City Health Officer o Rural Health Physician bilang requirement para sa trabaho, medical assistance, o iba pang layunin.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => false, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],

            // Office 16 - AGRICULTURE
            ['office_id' => 16, 'service_name' => 'Registration of Farmers to Registry System for Basic Sector in Agriculture (RSBSA)', 'service_code' => 'RSBSA', 'service_description' => 'Register farmers.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 16, 'service_name' => 'Provision of Technical Assistance on Crop Production Technologies and Management', 'service_code' => 'PTA-CPTM', 'service_description' => 'Crop assistance.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 16, 'service_name' => 'Provision of Agricultural Inputs', 'service_code' => 'PAI', 'service_description' => 'Seeds and fertilizers.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 16, 'service_name' => 'Capability Enhancement Program', 'service_code' => 'CEP', 'service_description' => 'Training for farmers.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 16, 'service_name' => 'Provision of Credit Assistance thru LPG Seeds', 'service_code' => 'PCA-LPGS', 'service_description' => 'Financial aid.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 16, 'service_name' => 'Provision of Farm Mechanization Services', 'service_code' => 'PFMS', 'service_description' => 'Machinery support.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],

            // Office 17 - VETERINARY
            ['office_id' => 17, 'service_name' => 'Anti Rabies Vaccination', 'service_code' => 'ARV', 'service_description' => 'Rabies vaccination.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 17, 'service_name' => 'Issuance of Veterinary Health Certificate', 'service_code' => 'IVHC', 'service_description' => 'Animal health cert.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => false, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 17, 'service_name' => 'Animal Health Consultation and Services', 'service_code' => 'AHCS', 'service_description' => 'Animal services.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 17, 'service_name' => 'Animal Control Operation', 'service_code' => 'ACO', 'service_description' => 'Animal regulation.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => false, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],

            // Office 18 - CSWDO
            ['office_id' => 18, 'service_name' => 'Assistance to Individual in Crisis Situation', 'service_code' => 'AICS', 'service_description' => 'Tulong sa indibidwal o pamilya sa krisis.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 17, 'is_locked' => true, 'provides_assistance' => true],
            ['office_id' => 18, 'service_name' => 'Request for Issuance of Social Case Study Report', 'service_code' => 'SCSR', 'service_description' => 'Pagproseso ng Social Case Study Report.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 4, 'is_locked' => true, 'provides_assistance' => false],
            ['office_id' => 18, 'service_name' => 'Request for Issuance of Sector ID and Booklets', 'service_code' => 'RSIB', 'service_description' => 'Pagbibigay ng ID at booklet sa kwalipikadong sektor.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 1, 'is_locked' => true, 'provides_assistance' => false],
            ['office_id' => 18, 'service_name' => 'Request for Issuance of Certificates', 'service_code' => 'RIC', 'service_description' => 'Pagproseso ng iba\'t ibang sertipiko.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 3, 'is_locked' => true, 'provides_assistance' => false],
            ['office_id' => 18, 'service_name' => 'Management of Referred Cases', 'service_code' => 'MRC', 'service_description' => 'Pagtanggap at pag-aasikaso ng referred cases.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 1, 'is_locked' => true, 'provides_assistance' => false],
            ['office_id' => 18, 'service_name' => 'Core Shelter Assistance Program', 'service_code' => 'CSAP', 'service_description' => 'Tulong pabahay sa nangangailangan.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 18, 'service_name' => 'Management of Cases with Court Order Granting Community Service', 'service_code' => 'MCCS', 'service_description' => 'Pangangasiwa sa cases na may utos ng korte.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 18, 'service_name' => 'Community-Based Development & Rehabilitation Program for Person who Used Drugs', 'service_code' => 'CBDRP-PWUD', 'service_description' => 'Rehabilitation program para sa dating gumagamit ng droga.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 1, 'is_locked' => true, 'provides_assistance' => false],

            // Office 19 - PESO
            ['office_id' => 19, 'service_name' => 'Employment Facilitation', 'service_code' => 'EF', 'service_description' => 'Tulong sa paghahanap ng trabaho.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 19, 'service_name' => 'Employer\'s Accreditation', 'service_code' => 'EA', 'service_description' => 'Pagproseso ng accreditation ng employer.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 19, 'service_name' => 'Workers Hiring for Infrastructure Projects', 'service_code' => 'WHIP', 'service_description' => 'Pagbibigay trabaho sa proyekto.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 19, 'service_name' => 'Job Posting Services', 'service_code' => 'JPS', 'service_description' => 'Pag-aanunsyo ng bakanteng trabaho.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 19, 'service_name' => 'Referral Services to Other Relevant Government Agencies', 'service_code' => 'RSRGA', 'service_description' => 'Referral sa ibang ahensya.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],

            // Office 20 - CPDO
            ['office_id' => 20, 'service_name' => 'Issuance of Site Zoning Certificate', 'service_code' => 'SZC', 'service_description' => 'Zoning certification.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => false, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 20, 'service_name' => 'Issuance of Locational Clearance for Building Permit', 'service_code' => 'LCBP', 'service_description' => 'Locational clearance for building permit.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => false, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 20, 'service_name' => 'Issuance of Preliminary and Locational Clearance', 'service_code' => 'PALC', 'service_description' => 'Paunang clearance for project location.', 'service_type' => 'External', 'classification' => 'Complex', 'is_free' => false, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 20, 'service_name' => 'Issuance of Development Permit', 'service_code' => 'DP', 'service_description' => 'Permit for development project.', 'service_type' => 'External', 'classification' => 'Complex', 'is_free' => false, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 20, 'service_name' => 'Issuance of Alteration Plan', 'service_code' => 'AP', 'service_description' => 'Approval of alteration plan.', 'service_type' => 'External', 'classification' => 'Complex', 'is_free' => false, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],

            // Office 21 - CDRRMO
            ['office_id' => 21, 'service_name' => 'Request for DRRM Trainings/Seminars/Orientation', 'service_code' => 'R-DTRSO', 'service_description' => 'DRRM trainings and orientation.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 21, 'service_name' => 'Request for DRRM Data for Research/Studies/IEC', 'service_code' => 'RDD-RSIEC', 'service_description' => 'Provision of DRRM data.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 21, 'service_name' => 'Review of BDRRM Plan/Fund and Certification', 'service_code' => 'RBPF-C', 'service_description' => 'Pagsusuri ng BDRRM plan at pondo.', 'service_type' => 'External', 'classification' => 'Highly_Technical', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 21, 'service_name' => 'Request for Emergency Rescue Services', 'service_code' => 'RERS', 'service_description' => 'Provision of rescue services.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 21, 'service_name' => 'Request for Patient Conduction', 'service_code' => 'RPC', 'service_description' => 'Transport ng pasyente.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 21, 'service_name' => 'Request for Standby Ambulance (Stand-by) for Activity', 'service_code' => 'RASA', 'service_description' => 'Standby ambulance allocation.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 21, 'service_name' => 'Request for Hazard, Risk, Vulnerability Assessment', 'service_code' => 'RHRVA', 'service_description' => 'Hazard and vulnerability assessment.', 'service_type' => 'External', 'classification' => 'Highly_Technical', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],

            // Office 22 - HRMO
            ['office_id' => 22, 'service_name' => 'Processing of Camineso Payroll', 'service_code' => 'PCP', 'service_description' => 'Payroll processing for Camineso workers.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 22, 'service_name' => 'Filing of SALN (Barangay Officials)', 'service_code' => 'FS', 'service_description' => 'Processing SALN of barangay officials.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 22, 'service_name' => 'Leave Application', 'service_code' => 'LA', 'service_description' => 'Leave application processing.', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 22, 'service_name' => 'Application for Monetization', 'service_code' => 'AM', 'service_description' => 'Monetization of leave credits.', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 22, 'service_name' => 'Issuance of Service Record/Certification', 'service_code' => 'ISRC', 'service_description' => 'Issuance of service record/certification.', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 22, 'service_name' => 'Terminal Leave Benefit Application', 'service_code' => 'ATLB', 'service_description' => 'Processing terminal leave benefits.', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 22, 'service_name' => 'Individual Performance Commitment Review', 'service_code' => 'IPCR', 'service_description' => 'Performance commitment processing.', 'service_type' => 'Internal', 'classification' => 'Highly_Technical', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 22, 'service_name' => 'Application for Pag-IBIG Number', 'service_code' => 'APHN', 'service_description' => 'Application for Pag-IBIG membership number.', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 22, 'service_name' => 'Application for Agency ID', 'service_code' => 'AAIC', 'service_description' => 'Agency ID processing.', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 22, 'service_name' => 'Job Order Payroll Processing', 'service_code' => 'PJOP', 'service_description' => 'Payroll for Job Order personnel.', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 22, 'service_name' => 'Issuance of Agency Clearance', 'service_code' => 'IAC', 'service_description' => 'Agency clearance issuance.', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 22, 'service_name' => 'Filing of SALN (City Officials & Employees)', 'service_code' => 'FSALN', 'service_description' => 'SALN processing for LGU employees.', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],

            // Office 23 - ACCOUNTING
            ['office_id' => 23, 'service_name' => 'Disbursement Process', 'service_code' => 'DP', 'service_description' => 'Fund disbursement.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 23, 'service_name' => 'Preparation of Disbursement Vouchers', 'service_code' => 'PDV', 'service_description' => 'Preparation of vouchers.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 23, 'service_name' => 'Preparation & Transmittal of Accountant Advice to Bank', 'service_code' => 'PTAADB', 'service_description' => 'Sending accountant advice to bank.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 23, 'service_name' => 'Issuance of Certificate of Taxes Withheld (Bir 2307)', 'service_code' => 'ICTW-2307', 'service_description' => 'BIR Form 2307 issuance.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 23, 'service_name' => 'Issuance of Certificate of Taxes Withheld (Bir 2316)', 'service_code' => 'ICTW-2316', 'service_description' => 'BIR Form 2316 issuance.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 23, 'service_name' => 'Recording & Submission of Barangay Financial Transactions to Coa', 'service_code' => 'RSBFT-COA', 'service_description' => 'Financial reporting to COA.', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 23, 'service_name' => 'Issuance of Clearance from Money, Property and Legal Accountabilities', 'service_code' => 'CLR01', 'service_description' => 'Pagpapatunay na walang financial at legal na obligasyon ang empleyado sa lungsod', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 23, 'service_name' => 'Issuance of Certificate of Premiums and Loan Amortizations Remittances to Gsis, Pag-Ibig, and Philhealth', 'service_code' => 'CERT01', 'service_description' => 'Sertipiko ng mga premium at loan amortizations na nairemit sa GSIS, Pag-IBIG at PhilHealth', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 23, 'service_name' => 'Assistance to City Officials and Employees of Their Loans Application to Pag-Ibig Fund', 'service_code' => 'LOAN01', 'service_description' => 'Tulong sa mga empleyado sa pag-apply ng Pag-IBIG loan', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 23, 'service_name' => 'Processing of Various Gsis Loans Application of City Officials and Employees', 'service_code' => 'GSIS01', 'service_description' => 'Pagproseso ng iba\'t ibang uri ng GSIS loan ng mga empleyado', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 23, 'service_name' => 'Monthly Remittance of Gsis, Pag-Ibig and Philhealth Premiums and Loan Amortizations', 'service_code' => 'REMIT01', 'service_description' => 'Buwanang pagpapadala ng premiums at loan payments sa GSIS, Pag-IBIG at PhilHealth', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 23, 'service_name' => 'Monthly and Annual Preparation of Alphalist Data Entry and Monthly Remittance of Taxes Withheld to the Bureau of Internal Revenue (Bir)', 'service_code' => 'BIR01', 'service_description' => 'Paghahanda ng alphalist at buwanang remittance ng withholding tax sa BIR', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 23, 'service_name' => 'Monthly Processing of Permanent and Casual Payroll and Uploading of Txt File to Findes Lbp Application of Generated Payroll Register As Well As That Payroll Processed from Various Offices/Department of the City of Ligao.', 'service_code' => 'PAY01', 'service_description' => 'Buwanang pagproseso ng payroll at pag-upload ng TXT file sa FINDES LBP', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 23, 'service_name' => 'Certification of Inventory Stock Availability and Status', 'service_code' => 'INV01', 'service_description' => 'Sertipikasyon ng available na stock at status ng inventory', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 23, 'service_name' => 'Receipt and Recording of Liquidations of Cash Advances Granted to City Officials and Employees', 'service_code' => 'LIQ01', 'service_description' => 'Pagtanggap at pagtala ng liquidation reports ng cash advances', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 23, 'service_name' => 'Reporting on the Status of Fund Utilization for Transferred Fund for Specific Purpose and Subject to Liquidation under Trust Account', 'service_code' => 'FUND01', 'service_description' => 'Ulat sa paggamit ng pondo na nasa ilalim ng trust account', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 23, 'service_name' => 'Preparation, Reporting and Submission of Financial Statements to the Commission on Audit, Office of the Mayor and Sangguniang Panlungsod.', 'service_code' => 'FS01', 'service_description' => 'Paghahanda at pagsusumite ng financial statements sa COA, Mayor at Sanggunian', 'service_type' => 'External', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 23, 'service_name' => 'Issuance of Clearance from Money, Property and Legal Accountabilities - Internal', 'service_code' => 'CLR01I', 'service_description' => 'Internal: Pagpapatunay na walang financial at legal na obligasyon ang empleyado', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 23, 'service_name' => 'Issuance of Certificate of Premiums and Loan Amortizations Remittances to Gsis, Pag-Ibig, and Philhealth - Internal', 'service_code' => 'CERT01I', 'service_description' => 'Internal: Sertipiko ng mga premium at loan amortizations na nairemit', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 23, 'service_name' => 'Assistance to City Officials and Employees of Their Loans Application to Pag-Ibig Fund - Internal', 'service_code' => 'LOAN01I', 'service_description' => 'Internal: Tulong sa empleyado sa Pag-IBIG loan application', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 23, 'service_name' => 'Processing of Various Gsis Loans Application of City Officials and Employees - Internal', 'service_code' => 'GSIS01I', 'service_description' => 'Internal: Pagproseso ng GSIS loan applications', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 23, 'service_name' => 'Monthly Remittance of Gsis, Pag-Ibig and Philhealth Premiums and Loan Amortizations - Internal', 'service_code' => 'REMIT01I', 'service_description' => 'Internal: Buwanang remittance ng premiums at loan payments', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 23, 'service_name' => 'Monthly and Annual Preparation of Alphalist Data Entry and Monthly Remittance of Taxes Withheld to the Bureau of Internal Revenue (Bir) - Internal', 'service_code' => 'BIR01I', 'service_description' => 'Internal: Paghahanda ng alphalist at BIR remittance', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 23, 'service_name' => 'Monthly Processing of Permanent and Casual Payroll and Uploading of Txt File to Findes Lbp Application of Generated Payroll Register As Well As That Payroll Processed from Various Offices/Department of the City of Ligao. - Internal', 'service_code' => 'PAY01I', 'service_description' => 'Internal: Buwanang payroll processing at FINDES LBP upload', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 23, 'service_name' => 'Certification of Inventory Stock Availability and Status - Internal', 'service_code' => 'INV01I', 'service_description' => 'Internal: Sertipikasyon ng inventory stock availability', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 23, 'service_name' => 'Receipt and Recording of Liquidations of Cash Advances Granted to City Officials and Employees - Internal', 'service_code' => 'LIQ01I', 'service_description' => 'Internal: Pagtanggap at pagtala ng cash advances liquidation', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 23, 'service_name' => 'Reporting on the Status of Fund Utilization for Transferred Fund for Specific Purpose and Subject to Liquidation under Trust Account - Internal', 'service_code' => 'FUND01I', 'service_description' => 'Internal: Ulat sa fund utilization ng trust account', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 23, 'service_name' => 'Preparation, Reporting and Submission of Financial Statements to the Commission on Audit, Office of the Mayor and Sangguniang Panlungsod. - Internal', 'service_code' => 'FS01I', 'service_description' => 'Internal: Paghahanda at pagsusumite ng financial statements', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],

            // Office 24 - BUDGET
            ['office_id' => 24, 'service_name' => 'Technical Review of Barangay and SK Budget', 'service_code' => 'TRBSB', 'service_description' => 'Review of barangay and SK budgets.', 'service_type' => 'External', 'classification' => 'Highly_Technical', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
            ['office_id' => 24, 'service_name' => 'Budget Execution Phase', 'service_code' => 'BEP', 'service_description' => 'Implementation of approved budget.', 'service_type' => 'Internal', 'classification' => 'Simple', 'is_free' => true, 'status' => 'active', 'used_count' => 0, 'is_locked' => false, 'provides_assistance' => false],
        ];

        foreach ($services as $service) {
            DB::table('services')->updateOrInsert(
                ['service_code' => $service['service_code']],
                [
                    'office_id' => $service['office_id'],
                    'service_name' => $service['service_name'],
                    'service_description' => $service['service_description'],
                    'service_type' => $service['service_type'],
                    'classification' => $service['classification'],
                    'is_free' => $service['is_free'],
                    'status' => $service['status'],
                    'used_count' => $service['used_count'],
                    'is_locked' => $service['is_locked'],
                    'provides_assistance' => $service['provides_assistance'],
                    'deleted_at' => null,
                    'updated_at' => now(),
                ]
            );
        }

        $this->command->info('Services seeded successfully! (' . count($services) . ' services)');
    }
}